#!/usr/bin/env bash
# Script that Installs nginx on the server

apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
