#!/usr/bin/env bash

terminator() {
	rm /var/run/myscript.pid
	exit
}
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"' SIGTERM
trap terminator SIGTERM SIGQUIT

echo "$$" > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
done
