#!/usr/bin/env bash
# Displays numbers from 1 to 20
#   if 4 displays "bad luck from China"
#   if 9 displays "bad luck from Japan"
#   if 17 displays "bad luck from Italy"

n=1

while [ $n -le 20 ]
do
  echo "$n"
  case $n in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( n++ ))
done
