#!/usr/bin/env bash
# Displays the contents of the current directory in list format.

for item in *; do
    if [ -f "$item" ] || [ -d "$item" ]; then
        name=$(echo "$item" | cut -d '-' -f 2-)
        echo "$name"
    fi
done
